audit_header: false
title: Lehigh Valley Real Estate Video Blog with Ken Varilek
description: Our mission at Home Partners Group is to be your best resource for Lehigh Valley real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Home Partners Group, your professional Lehigh Valley Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Ken Varilek
  title:
  license_number:
  about_markdown: |
    Hello, my name is Ken Varilek. My passion is to help buyers close the deal on their dream home. I am honored to help them get the best price, avoid the pitfalls, and close knowing that no stone was unturned and the purchase is a solid one. I have been a resident of the Lehigh Valley and a trusted business professional for over 25 years. As a Father of three, I understand the needs of a growing family. A house gives you shelter, but a home is where you hang jackets, build snowmen, and lay in the grass watching the clouds go by. It's that feeling you get when you walk through the door and get attacked with love by your furry best friend. I am proud to work, fish, hunt, and play here in Lehigh Valley. I am a member of Lehigh Valley Business Group, Lehigh Valley Association of Realtors, National Association of Realtors, Delaware River Smallmouth Group, Eastern PA Fishing Reports, and a Sponsoring Member. I love to make connections! Please feel free to give me a call and share your needs, wants, and dreams. I would be happy to provide you with a free consultation and a market analysis including the surrounding area and the value of your home.
  brand: Home Partners Group
  brokerage: eXp Realty
  market: Lehigh Valley
  address: 3426 Smith Hill Rd. Slatington, PA. 18080
  phone: 610-216-9898
  phone_type:
  phone2:
  phone2_type:
  email: ken.varilek@exprealty.com
  url: http://www.nicelehighvalleyhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://kenvarilek.exprealty.com/sell.php
  second_CTA_text: Home Search
  second_CTA_URL: https://kenvarilek.exprealty.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Lehigh Valley Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://kenvarilek.exprealty.com/sell.php

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Lehigh Valley Home?"
    CTA_text2: "Search the entire MLS for your Lehigh Valley home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://kenvarilek.exprealty.com/

lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lenderheadshot.jpg
  logo_path: /img/lenderlogo.png
  name: Luke Pickel
  license_number: NMLS 143399
  company: Buiness Development
  company_license_number:
  phone: 484-515-1015-1015
  email: lpickel@financeofamerica.com
  url: https://FOAmortgage.com/lpickel

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Lehigh Valley Real Estate Podcast with Ken Varilek'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Lehigh Valley Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Home Partners Group - your professional Lehigh Valley Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Lehigh Valley, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Ken Varilek'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Lehigh Valley Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#F58F1C' 
  theme_color: '#0E2656'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
